CREATE USER opal_infadm IDENTIFIED BY "&1"
DEFAULT TABLESPACE TS_APP_APM_DAT_U01
TEMPORARY TABLESPACE TEMP
PROFILE prof_usr
QUOTA UNLIMITED ON TS_APP_APM_DAT_U01
QUOTA UNLIMITED ON TS_APP_APM_IND_U01
/
