CREATE TABLE MAIL_ADDRESS_AUTH_INFO (
  MAIL_ADDRESS_AUTH_CODE VARCHAR2(64 CHAR) NOT NULL ,
  MAIL_ADDRESS_AUTH_KEY NUMBER(20) NOT NULL ,
  MAIL_ADDRESS_AUTH_SALT CHAR(20 CHAR) NOT NULL ,
  MAIL_ADDRESS_AUTH_EXPI_DATE TIMESTAMP NOT NULL ,
  PROCESS_DIVISION CHAR(1 CHAR) NOT NULL ,
  MAIL_ADDRESS VARCHAR2(200 CHAR) NOT NULL ,
  PROCESSED_FLAG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR),
  "VERSION" NUMBER(10) DEFAULT 0  NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
