CREATE TABLE MILE_INV_OBJ_TEMP_INFO (
  APPLICATION_MEMBER_ID NUMBER(10) NOT NULL ,
  MEMBER_CONTROL_NUMBER CHAR(10 CHAR),
  MEM_CTRL_NUM_BR_NUM CHAR(3 CHAR),
  OSAKA_PITAPA_NUMBER CHAR(10 CHAR),
  INVALID_OBJECT_MILE_AMOUNT NUMBER(7) DEFAULT 0  NOT NULL ,
  PROCESSED_FLAG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
