CREATE TABLE MAIN_USE_STA_INFO (
  MEMBER_CONTROL_NUMBER CHAR(10 CHAR) NOT NULL ,
  MEM_CTRL_NUM_BR_NUM CHAR(3 CHAR) NOT NULL ,
  LAST_TIME_REGIST_STATION_1 CHAR(3 CHAR),
  LAST_TIME_REGIST_STATION_2 CHAR(3 CHAR),
  LAST_TIME_REGIST_STATION_3 CHAR(3 CHAR),
  LAST_TIME_REGIST_STATION_4 CHAR(3 CHAR),
  LAST_TIME_REGIST_STATION_5 CHAR(3 CHAR),
  THIS_TIME_REGIST_STATION_1 CHAR(3 CHAR),
  THIS_TIME_REGIST_STATION_2 CHAR(3 CHAR),
  THIS_TIME_REGIST_STATION_3 CHAR(3 CHAR),
  THIS_TIME_REGIST_STATION_4 CHAR(3 CHAR),
  THIS_TIME_REGIST_STATION_5 CHAR(3 CHAR),
  MOVE_INFO_RIN_DATE CHAR(8 CHAR),
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR),
  "VERSION" NUMBER(10) DEFAULT 0  NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
