CREATE TABLE MILE_SUMMARY_INFORMATION (
  APPLICATION_MEMBER_ID NUMBER(10) NOT NULL ,
  MILE_SUM_YEAR_MONTH CHAR(6 CHAR) NOT NULL ,
  ACQUIRE_MILE_TOTAL NUMBER(7) NOT NULL ,
  USE_MILE_TOTAL NUMBER(7) NOT NULL ,
  LAST_MONTH_END_MILE_BALANCE NUMBER(7) NOT NULL ,
  THIS_MONTH_END_MILE_BALANCE NUMBER(7) NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
