CREATE TABLE FAMILY_MEM_SERVICE_INFO (
  FAMILY_MEM_SERVICE_CTRL_ID NUMBER(10) NOT NULL ,
  MEMBER_CONTROL_NUMBER CHAR(10 CHAR) NOT NULL ,
  APPLICANT_MEM_CTRL_NUM_BR_NUM CHAR(3 CHAR) NOT NULL ,
  RCPT_DATE_TIME TIMESTAMP NOT NULL ,
  REGIST_STATUS_DIVISION CHAR(1 CHAR) NOT NULL ,
  APPLY_START_DATE_TIME TIMESTAMP NOT NULL ,
  APPLY_END_DATE_TIME TIMESTAMP,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR),
  "VERSION" NUMBER(10) DEFAULT 0  NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
