CREATE TABLE ID_GENERATE (
  "ID" CHAR(4 CHAR) NOT NULL ,
  "NO" NUMBER(10) NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
