CREATE TABLE MAIL_ADDRESS_CHANGE_TEMP_INFO (
  MAIL_ADDRESS_CHANGE_RCPT_ID NUMBER(10) NOT NULL ,
  APPLICATION_MEMBER_ID NUMBER(10) NOT NULL ,
  MAIL_ADDRESS VARCHAR2(200 CHAR) NOT NULL ,
  PROCESSED_FLAG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
