CREATE TABLE MILE_ADJUST_INSTR_INFO (
  MILE_ADJUST_INSTR_ID NUMBER(10) NOT NULL ,
  APPLICATION_MEMBER_ID NUMBER(10) NOT NULL ,
  ADJUST_MILE_AMOUNT NUMBER(7) NOT NULL ,
  MILE_ADJUST_INSTR_DATE CHAR(8 CHAR) NOT NULL ,
  MILE_CATEGORY_CODE CHAR(3 CHAR) NOT NULL ,
  MILE_ADJUST_STATUS_DIVI CHAR(1 CHAR) NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR),
  "VERSION" NUMBER(10) DEFAULT 0  NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
