ALTER TABLE MESSAGE
  ADD CONSTRAINT PK_MESSAGE PRIMARY KEY
  (
    MESSAGE_ID,
    LANG
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_MESSAGE ON MESSAGE
    (
      MESSAGE_ID,
      LANG
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
