ALTER TABLE MILE_INV_OBJ_TEMP_INFO
  ADD CONSTRAINT PK_MILE_INV_OBJ_TEMP_INFO PRIMARY KEY
  (
    APPLICATION_MEMBER_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_MILE_INV_OBJ_TEMP_INFO ON MILE_INV_OBJ_TEMP_INFO
    (
      APPLICATION_MEMBER_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
