ALTER TABLE LOGIN_INFO_REREGIST_TEMP_INFO
  ADD CONSTRAINT PK_LOGIN_INFO_TEMP_INFO PRIMARY KEY
  (
    LOGIN_INFO_REREGIST_RCPT_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_LOGIN_INFO_TEMP_INFO ON LOGIN_INFO_REREGIST_TEMP_INFO
    (
      LOGIN_INFO_REREGIST_RCPT_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
