ALTER TABLE POST_INFORMATION
  ADD CONSTRAINT PK_POST_INFO PRIMARY KEY
  (
    POST_RECEIPT_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_POST_INFO ON POST_INFORMATION
    (
      POST_RECEIPT_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
