ALTER TABLE MILE_SUMMARY_INFORMATION
  ADD CONSTRAINT PK_MILE_SUMMARY_INFO PRIMARY KEY
  (
    APPLICATION_MEMBER_ID,
    MILE_SUM_YEAR_MONTH
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_MILE_SUMMARY_INFO ON MILE_SUMMARY_INFORMATION
    (
      APPLICATION_MEMBER_ID,
      MILE_SUM_YEAR_MONTH
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
