ALTER TABLE MAIL_PACK_DELIVER_INFO
  ADD CONSTRAINT PK_MAIL_PACK_DELIVER_INFO PRIMARY KEY
  (
    MAIL_PACK_DELIVER_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_MAIL_PACK_DELIVER_INFO ON MAIL_PACK_DELIVER_INFO
    (
      MAIL_PACK_DELIVER_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
