ALTER TABLE BUSINESS_DATE
  ADD CONSTRAINT PK_BUSINESS_DATE PRIMARY KEY
  (
    SEGMENT_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_BUSINESS_DATE ON BUSINESS_DATE
    (
      SEGMENT_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
