ALTER TABLE ID_GENERATE
  ADD CONSTRAINT PK_ID_GENERATE PRIMARY KEY
  (
    "ID"
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_ID_GENERATE ON ID_GENERATE
    (
      "ID"
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
