ALTER TABLE MILE_HISTORY_INFORMATION
  ADD CONSTRAINT PK_MILE_HISTORY_INFO PRIMARY KEY
  (
    MILE_HISTORY_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_MILE_HISTORY_INFO ON MILE_HISTORY_INFORMATION
    (
      MILE_HISTORY_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
