ALTER TABLE CODE_NAME
  ADD CONSTRAINT PK_CODE_NAME PRIMARY KEY
  (
    "ID",
    "VALUE",
    LANG
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_CODE_NAME ON CODE_NAME
    (
      "ID",
      "VALUE",
      LANG
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
