ALTER TABLE LOGIN_HISTORY_INFORMATION
  ADD CONSTRAINT PK_LOGIN_HISTORY_INFO PRIMARY KEY
  (
    LOGIN_HISTORY_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_LOGIN_HISTORY_INFO ON LOGIN_HISTORY_INFORMATION
    (
      LOGIN_HISTORY_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
