ALTER TABLE PARTNER_RIDE_APPLY_DATE
  ADD CONSTRAINT PK_PARTNER_RIDE_APPLY_DATE PRIMARY KEY
  (
    PARTNER_MEM_SERVICE_CTRL_ID,
    RIDE_APPLY_DATE
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_PARTNER_RIDE_APPLY_DATE ON PARTNER_RIDE_APPLY_DATE
    (
      PARTNER_MEM_SERVICE_CTRL_ID,
      RIDE_APPLY_DATE
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
