ALTER TABLE BATCH_REQUEST
  ADD CONSTRAINT PK_BATCH_REQUEST PRIMARY KEY
  (
    REQUEST_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_BATCH_REQUEST ON BATCH_REQUEST
    (
      REQUEST_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
