ALTER TABLE MVW_MILE_BALANCE_INFO
  ADD CONSTRAINT PK_MVW_MILE_BALANCE_INFO PRIMARY KEY
  (
    APPLICATION_MEMBER_ID,
    OBJECT_YEAR_MONTH
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_MVW_MILE_BALANCE_INFO ON MVW_MILE_BALANCE_INFO
    (
      APPLICATION_MEMBER_ID,
      OBJECT_YEAR_MONTH
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
