ALTER TABLE MILE_ADJUST_INSTR_INFO
  ADD CONSTRAINT PK_MILE_ADJUST_INSTR_INFO PRIMARY KEY
  (
    MILE_ADJUST_INSTR_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_MILE_ADJUST_INSTR_INFO ON MILE_ADJUST_INSTR_INFO
    (
      MILE_ADJUST_INSTR_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
