ALTER TABLE RIDE_UPPER_LIMIT_TIMES
  ADD CONSTRAINT PK_RIDE_UPPER_LIMIT_TIMES PRIMARY KEY
  (
    RIDE_APPLY_YEAR_MONTH,
    SERVICE_DIVISION
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_RIDE_UPPER_LIMIT_TIMES ON RIDE_UPPER_LIMIT_TIMES
    (
      RIDE_APPLY_YEAR_MONTH,
      SERVICE_DIVISION
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
