ALTER TABLE PUSH_NOTICE_INFORMATION
  ADD CONSTRAINT PK_PUSH_NOTICE_INFO PRIMARY KEY
  (
    PUSH_NOTICE_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_PUSH_NOTICE_INFO ON PUSH_NOTICE_INFORMATION
    (
      PUSH_NOTICE_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
