ALTER TABLE FAMILY_MEM_SERVICE_INFO
  ADD CONSTRAINT PK_FAMILY_MEM_SERVICE_INFO PRIMARY KEY
  (
    FAMILY_MEM_SERVICE_CTRL_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_FAMILY_MEM_SERVICE_INFO ON FAMILY_MEM_SERVICE_INFO
    (
      FAMILY_MEM_SERVICE_CTRL_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
