ALTER TABLE OP_MEM_INFO
  ADD CONSTRAINT PK_OP_MEM_INFO PRIMARY KEY
  (
    MEMBER_CONTROL_NUMBER,
    MEM_CTRL_NUM_BR_NUM
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_OP_MEM_INFO ON OP_MEM_INFO
    (
      MEMBER_CONTROL_NUMBER,
      MEM_CTRL_NUM_BR_NUM
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
