ALTER TABLE REQUEST
  ADD CONSTRAINT PK_REQUEST PRIMARY KEY
  (
    REQUEST_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX PK_REQUEST ON REQUEST
    (
      REQUEST_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
