language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/install-kaptcha-2.3.2.sh
- $HOME/build-script/travis-ci/setup-oracle-jdk6.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/install-james.sh
- $HOME/james-2.3.2.1/bin/phoenix.sh start
- $HOME/build-script/travis-ci/build-nablarch.sh -m deploy -p ci,dev-deploy
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: V8pWwXYeGD7y9YlTAWQ6gA4k7LXzx58WADsIEtQ+EoItQfm7x96mwbNRgkHopUlcfej1pxl1rALJ0yljIGDs+mLQQE8m15f+YpVOp8ygaUO9P48GaEMNQcH+AcPxyq9EW+vAa7bSRSKAG3vp9zPNodSrl9ch9+R9YnD5PwMG/a5dL75YeiufziwRkRjguznBPIBnr2jrQQRNQhkYpm8kgvuiStpLtdP9n48E2kT1QgHNgjQ5/rQFyyFMkAa+U9Pf7Smh6ZTMeESjtSfONfRKEyemU1jUN8PPRioMO6Kv6MYQgSCILgkb5dFzpBgJWvoSXIBJmHmhftPBhtW05MF+6Xnd0s0oh4Ftk94QCHNcgj614H+4iEVgWKp+Xj5lS3HARNkYAHrM8jXtCe50jA6V+DXhOBWbz1dOWSAq1B+Kw9uoIWHMFtM59YA7YpfNY+8C07VJzAD0vSUB3AyRgAD2rs3+64oxBEB6qp1wxgMtNaMhEkGv/KxzQIdml1SMhwR+hFBTnb3k2UTxC7/2VdLs1gLeo1ZwDHpA2k+3Be/cYjWHIIbQyQoaOh8byFDCCp9Hvkh8wg5Ybp7azCS+o7Qus6khO1PMmvXgbCIzsBoDUGHBBbDWLJ6fZPcdFyZ13xqbK4hSzbn8OGBL7Qt8E7ePm5J64GBJ8KkHAUhpkXvNLtg=
