CREATE SMALLFILE TABLESPACE TS_APP_APM_DAT_U01
  DATAFILE
    '/data/oradata/apmm/ts_app_apm_dat_u01_01.dbf' SIZE 8000M AUTOEXTEND ON NEXT 400M MAXSIZE 16000M
  EXTENT MANAGEMENT LOCAL
  UNIFORM SIZE 10M
  PERMANENT
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO
/
