CREATE SMALLFILE TABLESPACE TS_APP_APM_IND_U01
  DATAFILE
    '/data/oradata/apmm/ts_app_apm_ind_u01_01.dbf' SIZE 2000M AUTOEXTEND ON NEXT 100M MAXSIZE 4000M
  EXTENT MANAGEMENT LOCAL
  UNIFORM SIZE 10M
  PERMANENT
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO
/
