CREATE MATERIALIZED VIEW opal_apldba.MVW_MILE_BALANCE_INFO
TABLESPACE TS_APP_APM_DAT_U01
REFRESH FAST ON DEMAND AS
(
  SELECT
    APPLICATION_MEMBER_ID,
    OBJECT_YEAR_MONTH,
    MILE_BALANCE,
    INSERT_USER_ID,
    INSERT_DATE_TIME,
    UPDATE_USER_ID,
    UPDATE_DATE_TIME,
    DELETED_FLG,
    DELETED_DATE,
    "VERSION"
  FROM MILE_BALANCE_INFO
)
/
GRANT SELECT ON opal_apldba.MVW_MILE_BALANCE_INFO TO role_objsel
/
GRANT SELECT ON opal_apldba.MVW_MILE_BALANCE_INFO TO role_mvw
/
CREATE PUBLIC SYNONYM MVW_MILE_BALANCE_INFO FOR opal_apldba.MVW_MILE_BALANCE_INFO
/
