CREATE ROLE role_dbsel;
GRANT CREATE SESSION TO role_dbsel;
GRANT SELECT ANY DICTIONARY TO role_dbsel;
GRANT SELECT ON DBA_AUTO_SEGADV_CTL TO role_dbsel;
GRANT SELECT ON DBA_AUTO_SEGADV_SUMMARY TO role_dbsel;
GRANT SELECT ON ALL_SOURCE TO role_dbsel;
GRANT SELECT ON ROLE_ROLE_PRIVS TO role_dbsel;
GRANT SELECT ON USER_TAB_PRIVS TO role_dbsel;
GRANT SELECT ON USER_ROLE_PRIVS TO role_dbsel;
