CREATE ROLE role_sta;
GRANT SELECT ANY DICTIONARY TO role_sta;
GRANT ANALYZE ANY TO role_sta;
GRANT ANALYZE ANY DICTIONARY TO role_sta;
GRANT MANAGE SCHEDULER TO role_sta;
GRANT EXECUTE ON DBMS_STATS TO role_sta;
