CREATE PROFILE prof_usr LIMIT
 FAILED_LOGIN_ATTEMPTS 3
 PASSWORD_LIFE_TIME 90
 PASSWORD_REUSE_MAX 5
 PASSWORD_REUSE_TIME 365
 PASSWORD_LOCK_TIME 1
 PASSWORD_GRACE_TIME 3
 PASSWORD_VERIFY_FUNCTION ora12c_verify_function
/
