GRANT SELECT ON opal_apldba.PARTNER_MEM_SERVICE_INFO TO opal_lkcore
/
GRANT INSERT ON opal_apldba.PARTNER_MEM_SERVICE_INFO TO opal_lkcore
/
GRANT UPDATE ON opal_apldba.PARTNER_MEM_SERVICE_INFO TO opal_lkcore
/
