GRANT SELECT ON opal_apldba.FAMILY_MEM_SERVICE_INFO TO opal_lkcore
/
GRANT INSERT ON opal_apldba.FAMILY_MEM_SERVICE_INFO TO opal_lkcore
/
GRANT UPDATE ON opal_apldba.FAMILY_MEM_SERVICE_INFO TO opal_lkcore
/
