CREATE TABLE OPAL_APLDBA.PARTNER_RIDE_APPLY_DATE (
  PARTNER_MEM_SERVICE_CTRL_ID NUMBER(10) NOT NULL ,
  RIDE_APPLY_DATE CHAR(8 CHAR) NOT NULL ,
  RIDE_APPLY_YEAR_MONTH CHAR(6 CHAR) NOT NULL ,
  USER_CHOOSE_DIVISION CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.PARTNER_RIDE_APPLY_DATE TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.PARTNER_RIDE_APPLY_DATE TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.PARTNER_RIDE_APPLY_DATE TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.PARTNER_RIDE_APPLY_DATE TO role_objupd
/
CREATE PUBLIC SYNONYM PARTNER_RIDE_APPLY_DATE FOR OPAL_APLDBA.PARTNER_RIDE_APPLY_DATE
/
