CREATE TABLE OPAL_APLDBA.BUSINESS_DATE (
  SEGMENT_ID CHAR(2 CHAR) NOT NULL ,
  BIZ_DATE CHAR(8 CHAR) NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.BUSINESS_DATE TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.BUSINESS_DATE TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.BUSINESS_DATE TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.BUSINESS_DATE TO role_objupd
/
CREATE PUBLIC SYNONYM BUSINESS_DATE FOR OPAL_APLDBA.BUSINESS_DATE
/
