CREATE TABLE OPAL_APLDBA.APL_MEM_RECEPT_HIST_INFO (
  APPLICATION_MEMBER_ID NUMBER(10) NOT NULL ,
  RECEPTION_COMMENT VARCHAR2(2000 CHAR),
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR),
  "VERSION" NUMBER(10) DEFAULT 0  NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.APL_MEM_RECEPT_HIST_INFO TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.APL_MEM_RECEPT_HIST_INFO TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.APL_MEM_RECEPT_HIST_INFO TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.APL_MEM_RECEPT_HIST_INFO TO role_objupd
/
CREATE PUBLIC SYNONYM APL_MEM_RECEPT_HIST_INFO FOR OPAL_APLDBA.APL_MEM_RECEPT_HIST_INFO
/
