CREATE TABLE OPAL_APLDBA.POST_INFORMATION (
  POST_RECEIPT_ID NUMBER(10) NOT NULL ,
  APPLICATION_MEMBER_ID NUMBER(10) NOT NULL ,
  APPLICATION_ID VARCHAR2(50 CHAR),
  POST_RECEIPT_REGIST_DATE_TIME TIMESTAMP NOT NULL ,
  POST_CATEGORY CHAR(2 CHAR) NOT NULL ,
  POST_CONTROL_NUMBER VARCHAR2(32 CHAR) NOT NULL ,
  POSTCODE CHAR(7 CHAR) NOT NULL ,
  ADDRESS VARCHAR2(140 CHAR) NOT NULL ,
  "NAME" VARCHAR2(20 CHAR) NOT NULL ,
  TELEPHONE_NUMBER VARCHAR2(15 CHAR) NOT NULL ,
  OTHER VARCHAR2(100 CHAR),
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.POST_INFORMATION TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.POST_INFORMATION TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.POST_INFORMATION TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.POST_INFORMATION TO role_objupd
/
CREATE PUBLIC SYNONYM POST_INFORMATION FOR OPAL_APLDBA.POST_INFORMATION
/
