CREATE TABLE OPAL_APLDBA.OP_MEM_INFO (
  MEMBER_CONTROL_NUMBER CHAR(10 CHAR) NOT NULL ,
  MEM_CTRL_NUM_BR_NUM CHAR(3 CHAR) NOT NULL ,
  OSAKA_PITAPA_NUMBER CHAR(10 CHAR) NOT NULL ,
  PITAPA_EXPIRATION_DATE CHAR(6 CHAR) NOT NULL ,
  OLD_PITAPA_EXPIRATION_DATE CHAR(6 CHAR),
  CARD_TYPE CHAR(4 CHAR) NOT NULL ,
  BIRTHDATE CHAR(8 CHAR) NOT NULL ,
  SEX_CODE CHAR(1 CHAR) NOT NULL ,
  TELEPHONE_NUMBER VARCHAR2(15 CHAR),
  CELLPHONE_NUMBER VARCHAR2(15 CHAR),
  POSTCODE CHAR(7 CHAR),
  SERVICE_CATEGORY CHAR(1 CHAR) NOT NULL ,
  REGIST_STATION_1 CHAR(3 CHAR),
  REGIST_STATION_2 CHAR(3 CHAR),
  RELATIONSHIP_CODE CHAR(1 CHAR) NOT NULL ,
  OSAKA_PITAPA_WITHDRAW_FLAG CHAR(1 CHAR) NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR),
  "VERSION" NUMBER(10) DEFAULT 0  NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.OP_MEM_INFO TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.OP_MEM_INFO TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.OP_MEM_INFO TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.OP_MEM_INFO TO role_objupd
/
CREATE PUBLIC SYNONYM OP_MEM_INFO FOR OPAL_APLDBA.OP_MEM_INFO
/
