CREATE TABLE OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO (
  MEMBER_CONTROL_NUMBER CHAR(10 CHAR) NOT NULL ,
  MEM_CTRL_NUM_BR_NUM CHAR(3 CHAR) NOT NULL ,
  REGIST_STATION_1 CHAR(3 CHAR),
  REGIST_STATION_2 CHAR(3 CHAR),
  REGIST_STATION_3 CHAR(3 CHAR),
  REGIST_STATION_4 CHAR(3 CHAR),
  REGIST_STATION_5 CHAR(3 CHAR),
  PROCESSED_FLAG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO TO role_objsel
/
GRANT INSERT ON OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO TO role_objupd
/
GRANT UPDATE ON OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO TO role_objupd
/
GRANT DELETE ON OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO TO role_objupd
/
CREATE PUBLIC SYNONYM MAIN_USE_STA_TEMP_INFO FOR OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO
/
