CREATE TABLE OPAL_APLDBA.RESPONSE_MESSAGE (
  MESSAGE_ID VARCHAR2(64 CHAR) NOT NULL ,
  REQUEST_ID CHAR(10 CHAR) NOT NULL ,
  PROCESS_RESULT_CODE CHAR(3 CHAR) NOT NULL ,
  MESSAGE_HEAD BLOB NOT NULL ,
  MESSAGE_BODY BLOB NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.RESPONSE_MESSAGE TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.RESPONSE_MESSAGE TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.RESPONSE_MESSAGE TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.RESPONSE_MESSAGE TO role_objupd
/
CREATE PUBLIC SYNONYM RESPONSE_MESSAGE FOR OPAL_APLDBA.RESPONSE_MESSAGE
/
