CREATE TABLE OPAL_APLDBA.APL_MEM_INFO (
  APPLICATION_MEMBER_ID NUMBER(10) NOT NULL ,
  MEMBER_CONTROL_NUMBER CHAR(10 CHAR),
  MEM_CTRL_NUM_BR_NUM CHAR(3 CHAR),
  OSAKA_PITAPA_NUMBER CHAR(10 CHAR),
  APPLICATION_ID VARCHAR2(50 CHAR),
  DEVICE_ID VARCHAR2(7 CHAR),
  LOGIN_ID VARCHAR2(16 CHAR),
  "PASSWORD" VARCHAR2(64 CHAR),
  PASSWORD_SALT CHAR(20 CHAR),
  STRETCHING_TIMES NUMBER(1),
  BIRTHDATE CHAR(8 CHAR),
  SEX_CODE CHAR(1 CHAR),
  MAIL_ADDRESS VARCHAR2(200 CHAR),
  MAIL_DELIVER_STATUS_DIVISION CHAR(1 CHAR),
  RECOMMEND_USE_ACCEPT_FLAG CHAR(1 CHAR),
  ENQUETE_1 CHAR(3 CHAR),
  ENQUETE_2 CHAR(3 CHAR),
  ENQUETE_3 CHAR(3 CHAR),
  ENQUETE_4 CHAR(3 CHAR),
  ENQUETE_5 CHAR(3 CHAR),
  ENQUETE_6 CHAR(3 CHAR),
  ENQUETE_7 CHAR(3 CHAR),
  ENQUETE_8 CHAR(3 CHAR),
  ENQUETE_9 CHAR(3 CHAR),
  ENQUETE_10 CHAR(3 CHAR),
  MAIN_USE_STATION_1 CHAR(3 CHAR),
  MAIN_USE_STATION_2 CHAR(3 CHAR),
  MAIN_USE_STATION_3 CHAR(3 CHAR),
  MAIN_USE_STATION_4 CHAR(3 CHAR),
  MAIN_USE_STATION_5 CHAR(3 CHAR),
  DAY_OFF_1 CHAR(1 CHAR),
  DAY_OFF_2 CHAR(1 CHAR),
  APPLICATION_MEMBER_STATUS_CODE CHAR(1 CHAR),
  OSAKA_PITAPA_AUTHENTICATE_FLAG CHAR(1 CHAR) NOT NULL ,
  OSAKA_PITAPA_WITHDRAW_FLAG CHAR(1 CHAR) NOT NULL ,
  OP_AUTH_TIMES NUMBER(2) DEFAULT 0  NOT NULL ,
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR),
  "VERSION" NUMBER(10) DEFAULT 0  NOT NULL 
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.APL_MEM_INFO TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.APL_MEM_INFO TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.APL_MEM_INFO TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.APL_MEM_INFO TO role_objupd
/
CREATE PUBLIC SYNONYM APL_MEM_INFO FOR OPAL_APLDBA.APL_MEM_INFO
/
