CREATE TABLE OPAL_APLDBA.MAIL_DELIVER_TMPL_INFO (
  TEMPLATE_ID CHAR(10 CHAR) NOT NULL ,
  SUBJECT VARCHAR2(80 CHAR) NOT NULL ,
  "BODY" VARCHAR2(4000 CHAR) NOT NULL ,
  FROM_ADDRESS VARCHAR2(200 CHAR) NOT NULL ,
  FROM_NAME VARCHAR2(200 CHAR) NOT NULL ,
  VARIABLE_ITEM_NAME_1 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_2 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_3 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_4 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_5 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_6 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_7 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_8 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_9 VARCHAR2(200 CHAR),
  VARIABLE_ITEM_NAME_10 VARCHAR2(200 CHAR),
  INSERT_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  INSERT_DATE_TIME TIMESTAMP NOT NULL ,
  UPDATE_USER_ID VARCHAR2(20 CHAR) NOT NULL ,
  UPDATE_DATE_TIME TIMESTAMP NOT NULL ,
  DELETED_FLG CHAR(1 CHAR) DEFAULT 0  NOT NULL ,
  DELETED_DATE CHAR(8 CHAR)
)
TABLESPACE TS_APP_APM_DAT_U01
/
GRANT SELECT ON OPAL_APLDBA.MAIL_DELIVER_TMPL_INFO TO role_objsel
/
GRANT INSERT ON OPAL_APLDBA.MAIL_DELIVER_TMPL_INFO TO role_objupd
/
GRANT UPDATE ON OPAL_APLDBA.MAIL_DELIVER_TMPL_INFO TO role_objupd
/
GRANT DELETE ON OPAL_APLDBA.MAIL_DELIVER_TMPL_INFO TO role_objupd
/
CREATE PUBLIC SYNONYM MAIL_DELIVER_TMPL_INFO FOR OPAL_APLDBA.MAIL_DELIVER_TMPL_INFO
/
