ALTER TABLE OPAL_APLDBA.MAIL_LITE_DELIVER_INFO
  ADD CONSTRAINT PK_MAIL_LITE_DELIVER_INFO PRIMARY KEY
  (
    MAIL_LITE_DELIVER_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_MAIL_LITE_DELIVER_INFO ON OPAL_APLDBA.MAIL_LITE_DELIVER_INFO
    (
      MAIL_LITE_DELIVER_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
