ALTER TABLE OPAL_APLDBA.LOGIN_HISTORY_INFORMATION
  ADD CONSTRAINT PK_LOGIN_HISTORY_INFO PRIMARY KEY
  (
    LOGIN_HISTORY_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_LOGIN_HISTORY_INFO ON OPAL_APLDBA.LOGIN_HISTORY_INFORMATION
    (
      LOGIN_HISTORY_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
