ALTER TABLE OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO
  ADD CONSTRAINT PK_MAIN_USE_STA_TEMP_INFO PRIMARY KEY
  (
    MEMBER_CONTROL_NUMBER,
    MEM_CTRL_NUM_BR_NUM
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLTRN.PK_MAIN_USE_STA_TEMP_INFO ON OPAL_APLTRN.MAIN_USE_STA_TEMP_INFO
    (
      MEMBER_CONTROL_NUMBER,
      MEM_CTRL_NUM_BR_NUM
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
