ALTER TABLE OPAL_APLDBA.PUSH_NOTICE_DEST_INFO
  ADD CONSTRAINT PK_PUSH_NOTICE_DEST_INFO PRIMARY KEY
  (
    PUSH_NOTICE_ID,
    SEQUENCE_MEMBER
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_PUSH_NOTICE_DEST_INFO ON OPAL_APLDBA.PUSH_NOTICE_DEST_INFO
    (
      PUSH_NOTICE_ID,
      SEQUENCE_MEMBER
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
