ALTER TABLE OPAL_APLDBA.MAIL_ADDRESS_AUTH_INFO
  ADD CONSTRAINT PK_MAIL_ADDRESS_AUTH_INFO PRIMARY KEY
  (
    MAIL_ADDRESS_AUTH_CODE
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_MAIL_ADDRESS_AUTH_INFO ON OPAL_APLDBA.MAIL_ADDRESS_AUTH_INFO
    (
      MAIL_ADDRESS_AUTH_CODE
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
