ALTER TABLE OPAL_APLDBA.FAMILY_RIDE_APPLY_DATE
  ADD CONSTRAINT PK_FAMILY_RIDE_APPLY_DATE PRIMARY KEY
  (
    FAMILY_MEM_SERVICE_CTRL_ID,
    RIDE_APPLY_DATE
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_FAMILY_RIDE_APPLY_DATE ON OPAL_APLDBA.FAMILY_RIDE_APPLY_DATE
    (
      FAMILY_MEM_SERVICE_CTRL_ID,
      RIDE_APPLY_DATE
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
