ALTER TABLE OPAL_APLDBA.BUSINESS_DATE
  ADD CONSTRAINT PK_BUSINESS_DATE PRIMARY KEY
  (
    SEGMENT_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_BUSINESS_DATE ON OPAL_APLDBA.BUSINESS_DATE
    (
      SEGMENT_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
