ALTER TABLE OPAL_APLDBA.BATCH_REQUEST
  ADD CONSTRAINT PK_BATCH_REQUEST PRIMARY KEY
  (
    REQUEST_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_BATCH_REQUEST ON OPAL_APLDBA.BATCH_REQUEST
    (
      REQUEST_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
