ALTER TABLE OPAL_APLDBA.RESPONSE_MESSAGE
  ADD CONSTRAINT PK_RESPONSE_MESSAGE PRIMARY KEY
  (
    MESSAGE_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_RESPONSE_MESSAGE ON OPAL_APLDBA.RESPONSE_MESSAGE
    (
      MESSAGE_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
