ALTER TABLE OPAL_APLDBA.MILE_ADJUST_INSTR_INFO
  ADD CONSTRAINT PK_MILE_ADJUST_INSTR_INFO PRIMARY KEY
  (
    MILE_ADJUST_INSTR_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_MILE_ADJUST_INSTR_INFO ON OPAL_APLDBA.MILE_ADJUST_INSTR_INFO
    (
      MILE_ADJUST_INSTR_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
