ALTER TABLE OPAL_APLDBA.PUSH_NOTICE_INFORMATION
  ADD CONSTRAINT PK_PUSH_NOTICE_INFO PRIMARY KEY
  (
    PUSH_NOTICE_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_PUSH_NOTICE_INFO ON OPAL_APLDBA.PUSH_NOTICE_INFORMATION
    (
      PUSH_NOTICE_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
