ALTER TABLE OPAL_APLDBA.REQUEST
  ADD CONSTRAINT PK_REQUEST PRIMARY KEY
  (
    REQUEST_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_REQUEST ON OPAL_APLDBA.REQUEST
    (
      REQUEST_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
