ALTER TABLE OPAL_APLDBA.CODE_PATTERN
  ADD CONSTRAINT PK_CODE_PATTERN PRIMARY KEY
  (
    "ID",
    "VALUE"
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_CODE_PATTERN ON OPAL_APLDBA.CODE_PATTERN
    (
      "ID",
      "VALUE"
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
