ALTER TABLE OPAL_APLDBA.MAIN_USE_STA_INFO
  ADD CONSTRAINT PK_MAIN_USE_STA_INFO PRIMARY KEY
  (
    MEMBER_CONTROL_NUMBER,
    MEM_CTRL_NUM_BR_NUM
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_MAIN_USE_STA_INFO ON OPAL_APLDBA.MAIN_USE_STA_INFO
    (
      MEMBER_CONTROL_NUMBER,
      MEM_CTRL_NUM_BR_NUM
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
