ALTER TABLE OPAL_APLDBA.PARTNER_MEM_SERVICE_INFO
  ADD CONSTRAINT PK_PARTNER_MEM_SERVICE_INFO PRIMARY KEY
  (
    PARTNER_MEM_SERVICE_CTRL_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_PARTNER_MEM_SERVICE_INFO ON OPAL_APLDBA.PARTNER_MEM_SERVICE_INFO
    (
      PARTNER_MEM_SERVICE_CTRL_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
