ALTER TABLE OPAL_APLDBA.MILE_BALANCE_INFO
  ADD CONSTRAINT PK_MILE_BALANCE_INFO PRIMARY KEY
  (
    APPLICATION_MEMBER_ID,
    OBJECT_YEAR_MONTH
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_MILE_BALANCE_INFO ON OPAL_APLDBA.MILE_BALANCE_INFO
    (
      APPLICATION_MEMBER_ID,
      OBJECT_YEAR_MONTH
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
