ALTER TABLE OPAL_APLDBA.APL_MEM_TEMP_INFO
  ADD CONSTRAINT PK_APL_MEM_TEMP_INFO PRIMARY KEY
  (
    APL_MEM_REGIST_RCPT_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_APL_MEM_TEMP_INFO ON OPAL_APLDBA.APL_MEM_TEMP_INFO
    (
      APL_MEM_REGIST_RCPT_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
