ALTER TABLE OPAL_APLDBA.MAIL_ADDRESS_CHANGE_TEMP_INFO
  ADD CONSTRAINT PK_MAIL_ADR_CHG_TEMP_INFO PRIMARY KEY
  (
    MAIL_ADDRESS_CHANGE_RCPT_ID
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_MAIL_ADR_CHG_TEMP_INFO ON OPAL_APLDBA.MAIL_ADDRESS_CHANGE_TEMP_INFO
    (
      MAIL_ADDRESS_CHANGE_RCPT_ID
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
