ALTER TABLE OPAL_APLDBA.MESSAGE
  ADD CONSTRAINT PK_MESSAGE PRIMARY KEY
  (
    MESSAGE_ID,
    LANG
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_MESSAGE ON OPAL_APLDBA.MESSAGE
    (
      MESSAGE_ID,
      LANG
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
