ALTER TABLE OPAL_APLTRN.PITAPA_USE_RES_TEMP_INFO
  ADD CONSTRAINT PK_PITAPA_USE_RES_TEMP_INFO PRIMARY KEY
  (
    MEMBER_CONTROL_NUMBER,
    MEM_CTRL_NUM_BR_NUM,
    PITAPA_USE_YEAR_MONTH
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLTRN.PK_PITAPA_USE_RES_TEMP_INFO ON OPAL_APLTRN.PITAPA_USE_RES_TEMP_INFO
    (
      MEMBER_CONTROL_NUMBER,
      MEM_CTRL_NUM_BR_NUM,
      PITAPA_USE_YEAR_MONTH
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
