ALTER TABLE OPAL_APLDBA.RIDE_UPPER_LIMIT_TIMES
  ADD CONSTRAINT PK_RIDE_UPPER_LIMIT_TIMES PRIMARY KEY
  (
    RIDE_APPLY_YEAR_MONTH,
    SERVICE_DIVISION
  )
  USING INDEX (
    CREATE UNIQUE INDEX OPAL_APLDBA.PK_RIDE_UPPER_LIMIT_TIMES ON OPAL_APLDBA.RIDE_UPPER_LIMIT_TIMES
    (
      RIDE_APPLY_YEAR_MONTH,
      SERVICE_DIVISION
    )
    TABLESPACE TS_APP_APM_IND_U01
  )
/
