CREATE PROFILE prof_apl LIMIT
 FAILED_LOGIN_ATTEMPTS 1
 PASSWORD_LIFE_TIME UNLIMITED
 PASSWORD_REUSE_MAX UNLIMITED
 PASSWORD_REUSE_TIME UNLIMITED
 PASSWORD_LOCK_TIME UNLIMITED
 PASSWORD_GRACE_TIME UNLIMITED
/
